#this query returns the name of a language
prefix : <http://langelin.org/ns/v1#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?lang_name
WHERE {
  :l0015 rdfs:label ?lang_name .
}
