#this query returns the parameters with their values for a single language
prefix : <http://langelin.org/ns/v1#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?lang ?param ?value
WHERE {
  ?lang :languageParameters :b0053 .
  :b0053 ?param ?value .
}
