#this query returns the description of a parameter
prefix : <http://langelin.org/ns/v1#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?param_description
WHERE {
  ?param :number "PARAMNUMBERHERE".
  ?param rdfs:description ?param_description.
}
