#this query returns the description of a question (i.e. the actual question in words)
prefix : <http://langelin.org/ns/v1#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?question_description
WHERE {
  ?param :number "PARAMNUMBERHERE".
  ?param :paramQuestion ?question.
  ?question :letter "QUESTIONLETTERHERE".
  ?question rdfs:description ?question_description.
}
